# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMLD <- function(L, K1, rho1, rho2, times, minus_log_runif_L, nT, dt) {
    .Call('_SimulateHAT_getMLD', PACKAGE = 'SimulateHAT', L, K1, rho1, rho2, times, minus_log_runif_L, nT, dt)
}

SimulateOnce <- function(L, T, K, seed) {
    .Call('_SimulateHAT_SimulateOnce', PACKAGE = 'SimulateHAT', L, T, K, seed)
}

SimulateIndirect <- function(L, T, K, seed) {
    .Call('_SimulateHAT_SimulateIndirect', PACKAGE = 'SimulateHAT', L, T, K, seed)
}

